### PR TITLE
Update optim

### LINKED ISSUE #194: Update optim_flat with local changes
E.g. adding the progress bar.

### PR DESCRIPTION
**Pull request by jobrachem**
Closes #194 

The changes are:

1. The function now includes a progress bar
2. The function now avoids including the model state into the compiled functions

### CODE REVIEW

**Comment by jobrachem** [comment]
@GianmarcoCallegher yesterday, I found some more issues, so I converted the PR back to a draft and fixed them. It is now ready for review. The issues concerned:

1. The implementation of early stopping contained a thinko. I had compared the current loss to the best loss within the patience periord. Now I compared the oldest loss in the patience period to the best loss within the patience period.
2. The iteration counter and index handling was off by one. Now, iteration 0 refers to the initial values. Previously it referred to the values after the first update.

**Comment by GianmarcoCallegher** [comment]
@jobrachem I saw new commits. Is it ready for the review?

**Comment by jobrachem** [comment]
@GianmarcoCallegher Yes :)

**Comment by GianmarcoCallegher** [comment]
Well done 😄

**Pull request merged**
