### PR TITLE
Rename Param and Obs

### LINKED ISSUE #53: Rename helper functions: Param -> param
We have some helper functions that are capitalized at the moment. Users might expect them to be classes because of Python's naming conventions. This issue is about renaming them to avoid this confusion.

- [ ] Param -> param
- [ ] Obs -> obs
- [ ] Anything else?

### PR DESCRIPTION
**Pull request by jobrachem**
Closes #53 

Notes:

- Getting the documentation right was a little tricky, because Sphinx does not work well with two objects of the same name (except for case differences) in the same module.
- To deal with this, I moved `Param` and `Obs` to the `liesel.model.legacy` module. 
- The import paths for users are not affected. I made sure that `Param` and `Obs` are imported to `liesel.model.__init__.py`, so they can still be used as `lsl.Param` and `lsl.Obs`
- The two functions are marked as deprecated, issue `FutureWarnings` and are marked to be removed in v0.4.0, see #129

### CODE REVIEW

**Comment by jobrachem** [comment]
Hi @wiep, would you do the review on this one?

**Review by wiep — APPROVED** [review]
looks good to me. do you want me to build the documentation locally?

**Comment by jobrachem** [comment]
I think that's not necessary. 

I just added a changelog entry. If you approve, feel free to merge and delete the branch.

**Comment by wiep** [comment]
great. Just a note: We need to publish a new version when we update the manuscript on arxiv so that the manuscript and software are in sync.

**Pull request merged**
