### PR TITLE
Create a visual distinction for data flow into Calculators and Distributions

### PR DESCRIPTION
**Pull request by GianmarcoCallegher**

### CODE REVIEW

**Comment by jobrachem** [comment]
I would like to see what the result looks like ;)

**Comment by GianmarcoCallegher** [comment]
```

**Comment by GianmarcoCallegher** [comment]
> I'm not sure whether I correctly understand what the purpose is. Is this interpretation correct?
> 
> Arrows that represent input to a variable's distribution are colored in light grey now, to create a visual distinction from arrows that represent input to a variable's calculator. The latter are colored in black, like they used to be.

Yes

**Comment by jobrachem** [comment]
Thanks! Maybe then a legend entry for both cases would be nice, something like "black: Used in value", "grey: Used in distribution". What do you think?

**Comment by GianmarcoCallegher** [comment]
> Thanks! Maybe then a legend entry for both cases would be nice, something like "black: Used in value", "grey: Used in distribution". What do you think?

Sure

**Comment by GianmarcoCallegher** [comment]
You can check now

**Comment by jobrachem** [comment]
image

I like it. One additional question: Why do you write "Used in value or calculator"? Can an input node be used in another node's value without the use of a calculator?

**Comment by GianmarcoCallegher** [comment]
> image
> 
> I like it. One additional question: Why do you write "Used in value or calculator"? Can an input node be used in another node's value without the use of a calculator?

You are right, it's redundant. I fixed it

**Pull request merged**
