### PR TITLE
Fixes unexpected behaviour in plot_vars when using an intermediate Calc

### PR DESCRIPTION
**Pull request by GianmarcoCallegher**

### CODE REVIEW

**Comment by jobrachem** [comment]
Hey @GianmarcoCallegher thanks for the PR! Could you provide some of your testing code for me to run?

**Comment by GianmarcoCallegher** [comment]
Before providing any example test, I will try to follow Hannes' suggestion in #89

**Comment by jobrachem** [comment]
Alright, that would be nice :) I'll then convert this PR back to draft status for the time being. Just re-request review once it is ready.

**Comment by wiep** [comment]
Why was this closed? No longer relevant, new PR?

**Comment by GianmarcoCallegher** [comment]
My bad. I just wanted to delete the branch but obviously it also closed the PR. I reopened it

**Comment by GianmarcoCallegher** [comment]
@jobrachem it is ready for the review. I didn't adopt the solution proposed in #89 (probably because it doesn't work). This is a test file:

[tests_file.py.zip](https://github.com/liesel-devs/liesel/files/14741075/tests_file.py.zip)

**Comment by jobrachem** [comment]
Thanks @GianmarcoCallegher , the plots in the example script look good!

## Example 1:

image

Grey line from `sigma_sq` to `rent` as expected.

## Example 2:

image

Grey line from `sigma_sq` to `sigma` and from `sigma` to `rent` as expected. The black lines from `b` and `a` to `sigma_sq` are correct, but will likely be omitted once #174 progresses.

## Example 2, turning `sigma` from a Var into a pure Calc

image

Grey line from `sigma_sq` to `rent` as expected.


## Conclusion

Everything looks good to me! Just one request: Would you already add a line about this change to the changelog?

**Comment by GianmarcoCallegher** [comment]
> Thanks @GianmarcoCallegher , the plots in the example script look good!
> 
> ## Example 1:
> image
> 
> Grey line from `sigma_sq` to `rent` as expected.
> 
> ## Example 2:
> image
> 
> Grey line from `sigma_sq` to `sigma` and from `sigma` to `rent` as expected. The black lines from `b` and `a` to `sigma_sq` are correct, but will likely be omitted once #174 progresses.
> 
> ## Example 2, turning `sigma` from a Var into a pure Calc
> image
> 
> Grey line from `sigma_sq` to `rent` as expected.
> 
> ## Conclusion
> Everything looks good to me! Just one request: Would you already add a line about this change to the changelog?

Thanks a lot. Done it ❤️

**Pull request merged**
