### PR TITLE
adds an implementation of an interface for pymc models

### PR DESCRIPTION
**Pull request by wiep**

### CODE REVIEW

**Comment by wiep** [comment]
@jobrachem, how can i build the docs? I'd like to adjust them to make sure they look good before merging.

**Comment by jobrachem** [comment]
> @jobrachem, how can i build the docs? I'd like to adjust them to make sure they look good before merging.

[Here](https://github.com/liesel-devs/liesel-internal/wiki/Documentation-Guides#render-the-docs) is a short description. Currently the Sphinx docs are available only in the branch `sphinx-docs`. Maybe to view your docs it is therefore easiest to merge the `sphinx-docs` branch into your current branch.

**Comment by wiep** [comment]
This branch is based on the new sphinx-docs (the `sphinx-docs` branch). Thus, it should not be merged before we switch to sphinx docs.

**Comment by wiep** [comment]
i force pushed the branch to remove the changes i've pulled in from `sphinx-docs`.

**Review by jobrachem — APPROVED** [review]

**Pull request merged**
